### PR TITLE
Add retry logic to elastic search calls

### PR DESCRIPTION
**Pull request by tybritten**
We've had an occasional problem where a request to ES gets mangled somehow (unexpected EOF) which causes indexer to re-index. 
The new code leverages Hashicorp's retryablehttp package, with the following settings:
*max 4 retries
*do not retry on context.Canceled or context.DeadlineExceeded
*retry on 500s or invalid status codes
*retry if the body cannot be parsed.

Tests are included as well.

### CODE REVIEW

**Comment by rowanseymour** [comment]
Goflow and mailroom do retries of HTTP calls with functionality which now lives in https://github.com/nyaruka/goflow/tree/master/utils/httpx. For a while I've been wanting to move that to gocommon and use more widely in our Go projects. I think I'd prefer that that leaning on a third party module. 

@nicpottier ?

**Comment by tybritten** [comment]
oh sweet i can totally use that instead if you want.

**Comment by nicpottier** [comment]
The requests that are failing are presumably POSTs ya? Pulling the goflow retry sounds fine but you'll need to tweak the retry logic a tad to make sure those are actually retried.

**Comment by tybritten** [comment]
Yeah. I was thinking as long as we can override the default retry logic function after intitializing the client like I did here that gives us plenty of flexibility and avoid trying to cover too many cases with the default logic.

**Comment by tybritten** [comment]
Closing this PR and starting over with `httpx`

**Comment by rowanseymour** [comment]
Cool - note that `httpx` let's you provide a func to the RetryConfig which determines whether it should be retried so shouldn't be any problem customizing that. I'll move `httpx` to gocommon shortly.

**Comment by tybritten** [comment]
Can you also move the `goflow/http` client creation stuff from mailroom there too? Imho its better to build the client with defaults, but override them if needed. vs doing that in each project
```
newclient := httpx.NewClient()
newclient.RetryConfig =......
```

**Comment by rowanseymour** [comment]
I've moved a bunch of functionality from goflow to gocommon and that's released as https://github.com/nyaruka/gocommon/releases/tag/v1.3.0

I looked at the client instantiating stuff but I'd rather leave that as is for now..

**Comment by tybritten** [comment]
@rowanseymour would you prefer I match the setup to MR? `goflow/http.go`?

**Comment by rowanseymour** [comment]
Well whatever we think is most appropriate for calls to elasticsearch server.. I don't think it needs most of those settings. Do we have any idea what was causing the request failures previously?

**Comment by tybritten** [comment]
Sorry, I meant package layout, etc. I have the retry logic customized and ported over- The failures are 99.9% of the time unexpected EOFs.

**Comment by rowanseymour** [comment]
I think it's ok to keep rp-indexer's layout simpler.. just stick it at the top of indexer.go

**Pull request closed without merging**
